
name: nhts-ctgan
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas>=2.0
  - numpy>=1.24
  - matplotlib>=3.8
  - scikit-learn>=1.4
  - pytorch>=2.2
  - scipy>=1.11
  - pip
  - pip:
      - sdv>=1.10.0
      - streamlit>=1.35.0
